version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - SUPABASE_URL=https://zycfjdfjnslklfujqmsz.supabase.co
      - REDIS_HOST=redis  # Set to Docker service name
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/node-app

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

